image: node:8.11.3

before_script:
    - npm install

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
    - node_modules/


test_app_deploy:
    script:
       - npm run build_test_env
       - npm run set_development_environment
       - npm run deploy_to_dev
    only:
       - development

firebase_deploy:
     script:
        - npm run build_prod_env
        - npm run set_production_environment
        - npm run deploy_to_prod
     only:
        - master
